# Copyright 2026 JIALE LIU (upstream); fork additions for SOLIDWORKS 2017 support.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Static (offline) check that the server only calls SOLIDWORKS 2017 API members.

The server talks to SOLIDWORKS by late binding, so a name that does not exist
in the installed release does not fail at import time: it fails (or, worse,
silently no-ops inside a bare ``except``) only when a user calls that tool.
This test turns that into a build-time failure.

It parses every ``solidworks_mcp/*.py`` with ``ast`` and collects every name
the code could send to COM:

* PascalCase attribute accesses and calls (``ext.SelectByID2(...)``);
* member names passed as strings to the late-binding helpers (``flag_methods``,
  ``value``, ``safe``, ``feature_property``, ``invoke_no_arg``, ``getattr``);
* the ``_*_METHODS`` flag tuples and dispatch dicts;
* the candidate names handed to ``call_versioned`` (at least one must exist);
* member names iterated from a literal tuple and then passed to one of those
  helpers by variable (``for member in ("GetStartVertex", ...): value(e, member)``).

Each name must appear in ``tools/compat/sw2017_api_members.txt`` (generated by
``tools/compat/dump_sw_tlb.py`` from the installed 2017 type libraries).  Where
the receiver's interface is known (``extension(doc)`` is an IModelDocExtension,
``feature_manager(doc)`` an IFeatureManager, ...) the name is checked against
that interface alone; otherwise any interface will do.  Names that are not
SOLIDWORKS members at all go in ``tools/compat/compat_allowlist.txt`` with a
reason.

No SOLIDWORKS instance is needed or touched.
"""

from __future__ import annotations

import ast
import re
import sys
import unittest
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = ROOT / "solidworks_mcp"
MEMBERS_FILE = ROOT / "tools" / "compat" / "sw2017_api_members.txt"
ALLOWLIST_FILE = ROOT / "tools" / "compat" / "compat_allowlist.txt"

# ---------------------------------------------------------------------------
# What the scanner knows about receivers.
# ---------------------------------------------------------------------------

# Helper functions in sw_core that return a flagged COM object of known type.
HELPER_RETURNS = {
    "extension": ("IModelDocExtension",),
    "sketch_manager": ("ISketchManager",),
    "feature_manager": ("IFeatureManager",),
    "running_app": ("ISldWorks",),
}

# Properties that hand back a manager of known type.
PROPERTY_RETURNS = {
    "Extension": ("IModelDocExtension",),
    "SketchManager": ("ISketchManager",),
    "FeatureManager": ("IFeatureManager",),
    "SelectionManager": ("ISelectionMgr",),
    "ConfigurationManager": ("IConfigurationManager",),
}

# A document handle (``doc``) may be any of these; the application handle
# (``app``) is an ISldWorks.  Using the union keeps the check interface-specific
# without pretending to know which document type a tool received.
DOCUMENT_INTERFACES = ("IModelDoc2", "IPartDoc", "IAssemblyDoc", "IDrawingDoc")
NAME_RECEIVERS = {
    "ext": ("IModelDocExtension",),
    "app": ("ISldWorks",),
    "doc": DOCUMENT_INTERFACES,
}

# Module-level flag tuples and the interface(s) their members live on.
FLAG_TUPLE_INTERFACES = {
    "_SKETCH_MANAGER_METHODS": ("ISketchManager",),
    "_FEATURE_MANAGER_METHODS": ("IFeatureManager",),
    "_EXTENSION_METHODS": ("IModelDocExtension",),
    "_MODEL_DOC_METHODS": DOCUMENT_INTERFACES,
    "_APP_METHODS": ("ISldWorks",),
    # Offered to the drawing document, but a few (SelectEntity, GetFirstView...)
    # are flagged defensively for views as well.
    "_DRAWING_METHODS": DOCUMENT_INTERFACES + ("IView", "ISheet"),
    "_DIMENSION_METHODS": DOCUMENT_INTERFACES,
}
# Names the code calls that are CONFIRMED absent from 2017 but not yet fixed
# (docs/reports/phase2-static-compat.md).  They are real SOLIDWORKS-API mistakes,
# not Python noise, so they must not hide in compat_allowlist.txt.  The main test
# tolerates them; test_known_misses_are_fixed below fails while any remain.
# Currently empty: ViewDisplayShadedwithedges and TangentEdgeDisplay were fixed
# in Phase 2 (implementer C).  Keep the mechanism for future confirmed misses.
KNOWN_2017_MISSES: dict[str, str] = {}
FLAG_TUPLE_RE = re.compile(r"^_[A-Z0-9_]*METHODS$")

# Helpers that take (obj, "Member", ...) and read/call that member.
MEMBER_ARG_HELPERS = {"value", "safe", "feature_property", "invoke_no_arg", "getattr"}

PASCAL_RE = re.compile(r"^(?:[A-Z]|[A-Z][A-Za-z0-9]*[a-z][A-Za-z0-9]*)$")


@dataclass(frozen=True)
class Ref:
    """One member name the code sends to COM."""

    name: str
    interfaces: tuple[str, ...]  # empty = receiver unknown, any interface will do
    where: str  # "file.py:line"
    how: str  # attribute | flag_methods | value | _X_METHODS | indirect | ...


@dataclass(frozen=True)
class VersionedCall:
    """One call_versioned(...) site: the candidate names, newest first."""

    candidates: tuple[str, ...]
    interfaces: tuple[str, ...]
    where: str


@dataclass
class Scan:
    refs: list[Ref] = field(default_factory=list)
    versioned: list[VersionedCall] = field(default_factory=list)


# ---------------------------------------------------------------------------
# AST scanner.
# ---------------------------------------------------------------------------


def _imported_roots(tree: ast.AST) -> set[str]:
    """Names bound by ``import x`` / ``import x.y as z`` / ``from x import y``.

    An attribute chain that starts at one of these is a Python library, not a
    SOLIDWORKS object (``pythoncom.Nothing``, ``win32com.client.VARIANT``).
    """
    roots: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                roots.add((alias.asname or alias.name).split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            for alias in node.names:
                roots.add(alias.asname or alias.name)
    return roots


def _chain_root(node: ast.AST) -> str | None:
    while isinstance(node, ast.Attribute):
        node = node.value
    return node.id if isinstance(node, ast.Name) else None


def _expr_interfaces(node: ast.AST, local_types: dict[str, tuple[str, ...]]) -> tuple[str, ...]:
    """Best-effort interface(s) of an expression; empty tuple = unknown."""
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
        return HELPER_RETURNS.get(node.func.id, ())
    if isinstance(node, ast.Attribute):
        return PROPERTY_RETURNS.get(node.attr, ())
    if isinstance(node, ast.Name):
        if node.id in local_types:
            return local_types[node.id]
        return NAME_RECEIVERS.get(node.id, ())
    return ()


def _walk_scope(func: ast.AST):
    """ast.walk limited to one function's own body (nested defs are scanned on their own)."""
    stack = list(ast.iter_child_nodes(func))
    while stack:
        node = stack.pop()
        yield node
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda)):
            continue
        stack.extend(ast.iter_child_nodes(node))


def _local_types(func: ast.AST) -> dict[str, tuple[str, ...]]:
    """Types of locals assigned from a known accessor (``manager = feature_manager(doc)``)."""
    types: dict[str, tuple[str, ...]] = {}
    for node in _walk_scope(func):
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            found = _expr_interfaces(node.value, {})
            if found:
                types[node.targets[0].id] = found
    return types


def _str_const(node: ast.AST) -> str | None:
    return node.value if isinstance(node, ast.Constant) and isinstance(node.value, str) else None


def _str_consts(node: ast.AST) -> list[str]:
    """String literal(s) an expression can evaluate to: a constant, or both arms of ``"A" if c else "B"``."""
    if isinstance(node, ast.IfExp):
        return _str_consts(node.body) + _str_consts(node.orelse)
    text = _str_const(node)
    return [text] if text is not None else []


def _scan_function(func: ast.AST, fname: str, imported: set[str], scan: Scan) -> None:
    local_types = _local_types(func)

    def where(node: ast.AST) -> str:
        return f"{fname}:{getattr(node, 'lineno', '?')}"

    # Variables passed as the member argument to a member-reading helper, so a
    # literal tuple iterated into them can be traced (see For handling below).
    dynamic_member_vars: set[str] = set()

    for node in _walk_scope(func):
        if isinstance(node, ast.Attribute):
            if _chain_root(node) in imported:
                continue
            if PASCAL_RE.match(node.attr):
                scan.refs.append(
                    Ref(node.attr, _expr_interfaces(node.value, local_types), where(node), "attribute")
                )
        elif isinstance(node, ast.Call):
            func_name = node.func.id if isinstance(node.func, ast.Name) else None
            if func_name == "flag_methods" and node.args:
                interfaces = _expr_interfaces(node.args[0], local_types)
                for arg in node.args[1:]:
                    texts = _str_consts(arg)
                    for text in texts:
                        scan.refs.append(Ref(text, interfaces, where(node), "flag_methods"))
                    if not texts and isinstance(arg, ast.Name):
                        dynamic_member_vars.add(arg.id)
            elif func_name in MEMBER_ARG_HELPERS and len(node.args) >= 2:
                interfaces = _expr_interfaces(node.args[0], local_types)
                texts = _str_consts(node.args[1])
                for text in texts:
                    scan.refs.append(Ref(text, interfaces, where(node), func_name))
                if not texts and isinstance(node.args[1], ast.Name):
                    dynamic_member_vars.add(node.args[1].id)
            elif func_name == "call_versioned" and node.args:
                interfaces = _expr_interfaces(node.args[0], local_types)
                names: list[str] = []
                for candidate in node.args[1:]:
                    if isinstance(candidate, ast.Tuple) and candidate.elts:
                        text = _str_const(candidate.elts[0])
                        if text is not None:
                            names.append(text)
                if names:
                    scan.versioned.append(VersionedCall(tuple(names), interfaces, where(node)))
                    for name in names:
                        scan.refs.append(Ref(name, interfaces, where(node), "call_versioned"))

    # for member in ("A", "B"): value(obj, member)   /   for member, key in (("A", "a"), ...)
    for node in _walk_scope(func):
        if not isinstance(node, ast.For) or not isinstance(node.iter, (ast.Tuple, ast.List)):
            continue
        target = node.target
        positions: list[int] = []
        if isinstance(target, ast.Name) and target.id in dynamic_member_vars:
            positions = [-1]  # the element itself
        elif isinstance(target, ast.Tuple):
            positions = [i for i, t in enumerate(target.elts) if isinstance(t, ast.Name) and t.id in dynamic_member_vars]
        for element in node.iter.elts:
            for pos in positions:
                item = element if pos == -1 else (element.elts[pos] if isinstance(element, ast.Tuple) and pos < len(element.elts) else None)
                text = _str_const(item) if item is not None else None
                if text is not None:
                    scan.refs.append(Ref(text, (), where(element), "indirect (for-loop tuple)"))


def _scan_module_level(tree: ast.Module, fname: str, scan: Scan) -> None:
    """``_*_METHODS = (...)`` tuples and ``_*_METHODS = {...}`` dispatch dicts."""
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name) or not FLAG_TUPLE_RE.match(target.id):
            continue
        interfaces = FLAG_TUPLE_INTERFACES.get(target.id, ())
        values: list[ast.AST] = []
        if isinstance(node.value, (ast.Tuple, ast.List)):
            values = list(node.value.elts)
        elif isinstance(node.value, ast.Dict):
            values = list(node.value.values)
        for item in values:
            text = _str_const(item)
            if text is not None:
                scan.refs.append(Ref(text, interfaces, f"{fname}:{item.lineno}", target.id))


def scan_source(source: str, fname: str) -> Scan:
    """Scan one module's source text."""
    tree = ast.parse(source)
    imported = _imported_roots(tree)
    scan = Scan()
    _scan_module_level(tree, fname, scan)
    # Every function (including nested ones and methods) is scanned on its own,
    # so local-variable types are scoped to it.
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            _scan_function(node, fname, imported, scan)
    return scan


def scan_package() -> Scan:
    total = Scan()
    for path in sorted(PACKAGE_DIR.glob("*.py")):
        scan = scan_source(path.read_text(encoding="utf-8"), path.name)
        total.refs.extend(scan.refs)
        total.versioned.extend(scan.versioned)
    unique_refs = list(dict.fromkeys(total.refs))
    unique_versioned = list(dict.fromkeys(total.versioned))
    return Scan(unique_refs, unique_versioned)


# ---------------------------------------------------------------------------
# 2017 data.
# ---------------------------------------------------------------------------


def load_members() -> tuple[set[str], dict[str, set[str]]]:
    """(every bare member name, member names per interface) from the 2017 snapshot."""
    bare: set[str] = set()
    per_interface: dict[str, set[str]] = defaultdict(set)
    for line in MEMBERS_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or "." not in line:
            continue
        interface, _, member = line.partition(".")
        bare.add(member)
        per_interface[interface].add(member)
    return bare, per_interface


def load_allowlist() -> dict[str, str]:
    """name (or ``Interface.Member``) -> reason, from compat_allowlist.txt."""
    entries: dict[str, str] = {}
    if not ALLOWLIST_FILE.exists():
        return entries
    for raw in ALLOWLIST_FILE.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        name, _, reason = line.partition("#")
        entries[name.strip()] = reason.strip()
    return entries


def exists_in_2017(name: str, interfaces: tuple[str, ...], bare: set[str], per_interface: dict[str, set[str]]) -> bool:
    if interfaces:
        return any(name in per_interface.get(interface, ()) for interface in interfaces)
    return name in bare


def find_misses(scan: Scan, tolerate_known: bool = True) -> list[Ref]:
    bare, per_interface = load_members()
    allow = load_allowlist()
    misses = []
    for ref in scan.refs:
        if ref.how == "call_versioned":
            continue  # judged as a group, below
        if exists_in_2017(ref.name, ref.interfaces, bare, per_interface):
            continue
        if ref.name in allow:
            continue
        if tolerate_known and ref.name in KNOWN_2017_MISSES:
            continue
        misses.append(ref)
    return misses


def versioned_resolution(scan: Scan) -> list[tuple[VersionedCall, str | None]]:
    """For each call_versioned site, the first candidate that exists in 2017."""
    bare, per_interface = load_members()
    rows = []
    for call in scan.versioned:
        first = next(
            (name for name in call.candidates if exists_in_2017(name, call.interfaces, bare, per_interface)),
            None,
        )
        rows.append((call, first))
    return rows


def format_misses(misses: list[Ref]) -> str:
    lines = ["Names the code sends to COM that are NOT in the SOLIDWORKS 2017 type library:"]
    for ref in sorted(misses, key=lambda r: (r.name, r.where)):
        scope = "/".join(ref.interfaces) if ref.interfaces else "any interface"
        lines.append(f"  {ref.name:<34} {ref.where:<22} via {ref.how:<26} checked against: {scope}")
    lines.append(
        "Fix the call (use an older numbered variant, see sw_core.call_versioned), or, if it is a "
        "Python/pywin32 name rather than a SOLIDWORKS member, add it to tools/compat/compat_allowlist.txt "
        "with a reason."
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Tests.
# ---------------------------------------------------------------------------


class ApiCompatTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.scan = scan_package()

    def test_snapshot_is_present_and_looks_like_2017(self) -> None:
        bare, per_interface = load_members()
        self.assertGreater(len(bare), 5000, "sw2017_api_members.txt looks empty or truncated")
        # Two members whose absence/presence characterises 2017 (see ADR-0002).
        self.assertNotIn("SaveAs3", per_interface["IModelDocExtension"])
        self.assertIn("SaveAs", per_interface["IModelDocExtension"])
        self.assertIn("FeatureCut4", per_interface["IFeatureManager"])

    def test_scanner_finds_the_expected_volume_of_names(self) -> None:
        # Guards against the scanner silently going blind (e.g. an AST refactor
        # that makes it match nothing and so "passes").
        names = {ref.name for ref in self.scan.refs}
        self.assertGreater(len(self.scan.refs), 300)
        for expected in ("SelectByID2", "FeatureExtrusion3", "CreateLine", "GetMassProperties2",
                         "CreateSectionViewAt5", "EditRebuild3", "GetTypeName2"):
            self.assertIn(expected, names)
        self.assertGreaterEqual(len(self.scan.versioned), 6)

    def test_every_called_member_exists_in_sw2017(self) -> None:
        misses = find_misses(self.scan)
        if misses:
            print("\n" + format_misses(misses))
        self.assertEqual([], misses, format_misses(misses))

    def test_known_misses_are_fixed(self) -> None:
        # Fails while KNOWN_2017_MISSES names a member the source still calls that
        # 2017 lacks (see docs/reports/phase2-static-compat.md, section 2.6).
        misses = find_misses(self.scan, tolerate_known=False)
        self.assertEqual([], misses, format_misses(misses))

    def test_call_versioned_has_a_2017_candidate(self) -> None:
        rows = versioned_resolution(self.scan)
        unresolved = [call for call, first in rows if first is None]
        report = ["call_versioned sites (first candidate present in the 2017 typelib):"]
        for call, first in rows:
            report.append(f"  {call.where:<20} {' -> '.join(call.candidates):<62} resolves to: {first}")
        print("\n" + "\n".join(report))
        self.assertEqual(
            [],
            unresolved,
            "call_versioned sites where NO candidate exists in 2017:\n"
            + "\n".join(f"  {c.where}: {c.candidates}" for c in unresolved),
        )

    def test_allowlist_entries_are_not_real_2017_members(self) -> None:
        # An allowlisted name that IS a 2017 member is dead weight at best and,
        # at worst, would mask the day the member disappears from a snapshot.
        bare, per_interface = load_members()
        stale = []
        for entry in load_allowlist():
            if "." in entry:
                interface, _, member = entry.partition(".")
                present = member in per_interface.get(interface, ())
            else:
                present = entry in bare
            if present:
                stale.append(entry)
        self.assertEqual([], stale, f"Allowlist entries that exist in 2017 (remove them): {stale}")

    def test_allowlist_entries_have_reasons(self) -> None:
        missing = [name for name, reason in load_allowlist().items() if not reason]
        self.assertEqual([], missing, f"Allowlist entries without a '# reason': {missing}")

    def test_allowlist_entries_are_actually_used(self) -> None:
        used = {ref.name for ref in self.scan.refs}
        unused = [entry for entry in load_allowlist() if entry.split(".")[-1] not in used]
        self.assertEqual([], unused, f"Allowlist entries no source file references any more: {unused}")


class ScannerSelfTests(unittest.TestCase):
    """The scanner must flag a bad name; otherwise the real test proves nothing."""

    def _misses(self, source: str) -> set[str]:
        bare, per_interface = load_members()
        scan = scan_source(source, "fake.py")
        return {
            ref.name
            for ref in scan.refs
            if ref.how != "call_versioned" and not exists_in_2017(ref.name, ref.interfaces, bare, per_interface)
        }

    def test_flags_unknown_attribute_on_extension(self) -> None:
        source = "def f(doc):\n    ext = extension(doc)\n    ext.SaveAs9('x')\n"
        self.assertEqual({"SaveAs9"}, self._misses(source))

    def test_interface_specific_check_catches_wrong_receiver(self) -> None:
        # SaveAs3 exists in the typelib, but only on IModelDoc2, not on the extension.
        source = "def f(doc):\n    extension(doc).SaveAs3('x')\n"
        self.assertEqual({"SaveAs3"}, self._misses(source))

    def test_flags_unknown_name_in_flag_tuple(self) -> None:
        source = "_EXTENSION_METHODS = ('SelectByID2', 'BogusMember')\n"
        self.assertEqual({"BogusMember"}, self._misses(source))

    def test_flags_unknown_name_in_helper_strings(self) -> None:
        source = (
            "def f(obj):\n"
            "    flag_methods(obj, 'NopeOne')\n"
            "    value(obj, 'NopeTwo')\n"
            "    safe(obj, 'NopeThree')\n"
        )
        self.assertEqual({"NopeOne", "NopeTwo", "NopeThree"}, self._misses(source))

    def test_flags_unknown_name_iterated_into_helper(self) -> None:
        source = (
            "def f(edge):\n"
            "    for member, key in (('GetStartVertex', 'a'), ('GetNowhere', 'b')):\n"
            "        value(edge, member)\n"
        )
        self.assertEqual({"GetNowhere"}, self._misses(source))

    def test_ignores_python_library_attributes(self) -> None:
        source = "import pythoncom\n\ndef f():\n    return pythoncom.Nothing\n"
        self.assertEqual(set(), self._misses(source))

    def test_call_versioned_with_only_absent_names_is_unresolved(self) -> None:
        scan = scan_source(
            "def f(doc):\n    call_versioned(feature_manager(doc), ('FeatureCut99', ()), ('FeatureCut98', ()))\n",
            "fake.py",
        )
        bare, per_interface = load_members()
        self.assertEqual(1, len(scan.versioned))
        call = scan.versioned[0]
        self.assertFalse(any(exists_in_2017(n, call.interfaces, bare, per_interface) for n in call.candidates))


if __name__ == "__main__":
    unittest.main()
